export const themes = [
  {
    id: "one-piece",
    name: "One Piece",
    subtitle: "Cap sur Grand Line",
    symbol: "anchor",
    color: "#caa978",
  },
  {
    id: "games",
    name: "Jeux vidéo",
    subtitle: "À toi de jouer",
    symbol: "gamepad",
    color: "#b4acd8",
  },
  {
    id: "cinema",
    name: "Cinéma",
    subtitle: "De l’autre côté de l’écran",
    symbol: "film",
    color: "#d6a390",
  },
  {
    id: "history",
    name: "Histoire",
    subtitle: "Les échos du passé",
    symbol: "landmark",
    color: "#d3c28d",
  },
  {
    id: "geography",
    name: "Géographie",
    subtitle: "Le monde t’attend",
    symbol: "globe",
    color: "#8cbdb2",
  },
  {
    id: "science",
    name: "Sciences",
    subtitle: "Comprendre l’invisible",
    symbol: "atom",
    color: "#94b9d2",
  },
] as const;
export type ThemeId = (typeof themes)[number]["id"];
export type Question = {
  id: string;
  theme: ThemeId;
  text: string;
  choices: string[];
  correct: number;
  explanation: string;
};
type Row = [string, string, string, string, string, string];
// The correct answer is stored first in this editorial format. The game shuffles choices.
const bank: Record<ThemeId, Row[]> = {
  "one-piece": [
    [
      "Qui rêve de devenir le roi des pirates ?",
      "Monkey D. Luffy",
      "Roronoa Zoro",
      "Sanji",
      "Koby",
      "Luffy prend la mer pour trouver le One Piece et devenir le roi des pirates.",
    ],
    [
      "Qui a confié son chapeau de paille à Luffy ?",
      "Shanks",
      "Mihawk",
      "Garp",
      "Baggy",
      "Shanks confie son chapeau à Luffy et lui demande de le lui rendre lorsqu’il sera devenu un grand pirate.",
    ],
    [
      "Quel membre de l’équipage utilise trois sabres ?",
      "Zoro",
      "Usopp",
      "Chopper",
      "Franky",
      "Zoro pratique le Santoryu, un style de combat à trois sabres.",
    ],
    [
      "Quel est le métier de Nami à bord ?",
      "Navigatrice",
      "Médecin",
      "Cuisinière",
      "Archéologue",
      "Nami guide l’équipage grâce à ses connaissances en navigation et en météorologie.",
    ],
    [
      "Qui est le cuisinier de l’équipage ?",
      "Sanji",
      "Brook",
      "Franky",
      "Jinbe",
      "Sanji a appris la cuisine au Baratie, notamment auprès de Zeff.",
    ],
    [
      "Quel animal est Tony Tony Chopper ?",
      "Un renne",
      "Un ours",
      "Un cerf-volant",
      "Un lapin",
      "Chopper est un renne qui a mangé le fruit de l’humain.",
    ],
    [
      "Quel est le premier navire principal de l’équipage ?",
      "Going Merry",
      "Thousand Sunny",
      "Moby Dick",
      "Oro Jackson",
      "Le Going Merry précède le Thousand Sunny dans les aventures de l’équipage.",
    ],
    [
      "Qui est l’archéologue de l’équipage ?",
      "Nico Robin",
      "Nami",
      "Vivi",
      "Perona",
      "Nico Robin recherche la véritable histoire et sait lire les ponéglyphes.",
    ],
    [
      "Qui a créé le manga One Piece ?",
      "Eiichiro Oda",
      "Akira Toriyama",
      "Masashi Kishimoto",
      "Tite Kubo",
      "Eiichiro Oda est l’auteur et le dessinateur de One Piece.",
    ],
    [
      "Quel musicien de l’équipage est un squelette ?",
      "Brook",
      "Franky",
      "Usopp",
      "Jinbe",
      "Brook est le musicien de l’équipage du Chapeau de paille.",
    ],
  ],
  games: [
    [
      "Quel héros incarne-t-on principalement dans The Legend of Zelda ?",
      "Link",
      "Zelda",
      "Ganondorf",
      "Tingle",
      "Link est le héros jouable principal de la série ; Zelda est la princesse qui lui donne son nom.",
    ],
    [
      "Quel studio a créé Minecraft ?",
      "Mojang",
      "Valve",
      "Ubisoft",
      "Bungie",
      "Minecraft est né chez Mojang, fondé par Markus Persson et ses associés.",
    ],
    [
      "Quel personnage est le frère de Mario ?",
      "Luigi",
      "Wario",
      "Toad",
      "Yoshi",
      "Luigi est le frère de Mario, reconnaissable à sa casquette verte.",
    ],
    [
      "Dans Pokémon, quel type possède Pikachu ?",
      "Électrik",
      "Feu",
      "Eau",
      "Plante",
      "Pikachu est un Pokémon de type Électrik.",
    ],
    [
      "Quel objet sert à capturer un Pokémon ?",
      "Une Poké Ball",
      "Un rubis",
      "Un anneau",
      "Une matéria",
      "Les Poké Balls permettent de capturer et de transporter les Pokémon.",
    ],
    [
      "Quelle série met en scène le Master Chief ?",
      "Halo",
      "Doom",
      "Mass Effect",
      "Metroid",
      "Le Master Chief, aussi appelé John-117, est un protagoniste de Halo.",
    ],
    [
      "Dans quel jeu trouve-t-on la ville de Rapture ?",
      "BioShock",
      "Portal",
      "Half-Life",
      "Fallout 3",
      "Rapture est la cité sous-marine qui sert de cadre à BioShock.",
    ],
    [
      "Quel jeu de réflexion utilise des blocs qui tombent ?",
      "Tetris",
      "Pac-Man",
      "Pong",
      "Space Invaders",
      "Dans Tetris, on place des tétriminos pour compléter des lignes.",
    ],
    [
      "Quelle entreprise a créé la PlayStation ?",
      "Sony",
      "Nintendo",
      "Sega",
      "Atari",
      "La PlayStation est une console de Sony, lancée au Japon en 1994.",
    ],
    [
      "Quel personnage bleu est la mascotte de Sega ?",
      "Sonic",
      "Kirby",
      "Mega Man",
      "Rayman",
      "Sonic est un hérisson bleu connu pour sa vitesse.",
    ],
  ],
  cinema: [
    [
      "Qui a réalisé Titanic, sorti en 1997 ?",
      "James Cameron",
      "Steven Spielberg",
      "Peter Jackson",
      "Ridley Scott",
      "James Cameron a réalisé Titanic, avec Leonardo DiCaprio et Kate Winslet.",
    ],
    [
      "Dans Star Wars, quelle arme utilisent les Jedi ?",
      "Un sabre laser",
      "Un trident",
      "Une baguette",
      "Un arc",
      "Le sabre laser est l’arme emblématique des Jedi.",
    ],
    [
      "Quel studio a produit Toy Story en 1995 ?",
      "Pixar",
      "DreamWorks",
      "Ghibli",
      "Aardman",
      "Toy Story est le premier long métrage de Pixar.",
    ],
    [
      "Qui accompagne Frodon jusqu’au Mordor ?",
      "Sam",
      "Boromir",
      "Gimli",
      "Théoden",
      "Sam Gamegie accompagne Frodon dans sa quête pour détruire l’Anneau.",
    ],
    [
      "Quel cinéaste a réalisé Le Voyage de Chihiro ?",
      "Hayao Miyazaki",
      "Isao Takahata",
      "Makoto Shinkai",
      "Satoshi Kon",
      "Hayao Miyazaki a réalisé ce film d’animation du studio Ghibli.",
    ],
    [
      "Quel personnage dit « Je suis ton père » à Luke ?",
      "Dark Vador",
      "Yoda",
      "Obi-Wan Kenobi",
      "Han Solo",
      "Dark Vador révèle sa paternité à Luke dans L’Empire contre-attaque.",
    ],
    [
      "Dans quel film rencontre-t-on le robot WALL-E ?",
      "WALL-E",
      "Cars",
      "Là-haut",
      "Vice-versa",
      "WALL-E est le petit robot compacteur du film Pixar du même nom.",
    ],
    [
      "Quel animal est Simba dans Le Roi lion ?",
      "Un lion",
      "Un tigre",
      "Un guépard",
      "Un léopard",
      "Simba est un jeune lion destiné à succéder à son père Mufasa.",
    ],
    [
      "Quel acteur incarne Jack Sparrow ?",
      "Johnny Depp",
      "Orlando Bloom",
      "Brad Pitt",
      "Tom Hanks",
      "Johnny Depp interprète le capitaine Jack Sparrow dans Pirates des Caraïbes.",
    ],
    [
      "Quel film de Spielberg présente un parc de dinosaures ?",
      "Jurassic Park",
      "Les Dents de la mer",
      "E.T.",
      "Minority Report",
      "Jurassic Park, sorti en 1993, adapte le roman de Michael Crichton.",
    ],
  ],
  history: [
    [
      "En quelle année a eu lieu la prise de la Bastille ?",
      "1789",
      "1815",
      "1914",
      "1492",
      "La Bastille a été prise le 14 juillet 1789.",
    ],
    [
      "Quelle civilisation a construit les pyramides de Gizeh ?",
      "Les Égyptiens",
      "Les Romains",
      "Les Mayas",
      "Les Vikings",
      "Les pyramides de Gizeh ont été construites dans l’Égypte antique.",
    ],
    [
      "Qui fut le premier empereur romain ?",
      "Auguste",
      "Jules César",
      "Néron",
      "Trajan",
      "Octave reçoit le titre d’Auguste en 27 avant notre ère et devient le premier empereur romain.",
    ],
    [
      "En quelle année le mur de Berlin est-il tombé ?",
      "1989",
      "1979",
      "1999",
      "1969",
      "L’ouverture du mur de Berlin a eu lieu le 9 novembre 1989.",
    ],
    [
      "Quel roi de France était surnommé le Roi-Soleil ?",
      "Louis XIV",
      "Louis XVI",
      "François Ier",
      "Henri IV",
      "Louis XIV, qui régna de 1643 à 1715, est surnommé le Roi-Soleil.",
    ],
    [
      "Quelle ville a été ensevelie par le Vésuve en 79 ?",
      "Pompéi",
      "Athènes",
      "Sparte",
      "Carthage",
      "Pompéi a été ensevelie lors de l’éruption du Vésuve en 79 de notre ère.",
    ],
    [
      "Qui a été couronné empereur en l’an 800 ?",
      "Charlemagne",
      "Clovis",
      "Napoléon",
      "Charles Martel",
      "Charlemagne est couronné empereur à Rome le 25 décembre 800.",
    ],
    [
      "Quel conflit commence en Europe en septembre 1939 ?",
      "La Seconde Guerre mondiale",
      "La guerre de Cent Ans",
      "La guerre de Crimée",
      "La Première Guerre mondiale",
      "L’invasion de la Pologne par l’Allemagne, le 1er septembre 1939, déclenche la guerre en Europe.",
    ],
    [
      "Quel navigateur atteint les Caraïbes en 1492 ?",
      "Christophe Colomb",
      "Vasco de Gama",
      "James Cook",
      "Jacques Cartier",
      "Christophe Colomb atteint les Caraïbes en 1492 lors de sa traversée de l’Atlantique.",
    ],
    [
      "Quel pays a offert la statue de la Liberté aux États-Unis ?",
      "La France",
      "L’Italie",
      "L’Espagne",
      "La Grèce",
      "La statue de la Liberté est un cadeau de la France, inauguré à New York en 1886.",
    ],
  ],
  geography: [
    [
      "Quelle est la capitale du Japon ?",
      "Tokyo",
      "Kyoto",
      "Osaka",
      "Séoul",
      "Tokyo est la capitale du Japon ; Kyoto fut une ancienne capitale impériale.",
    ],
    [
      "Quel est le plus grand océan de la Terre ?",
      "Le Pacifique",
      "L’Atlantique",
      "L’Indien",
      "L’Arctique",
      "Le Pacifique est le plus grand océan par sa superficie.",
    ],
    [
      "Dans quel pays se trouve le Machu Picchu ?",
      "Le Pérou",
      "Le Mexique",
      "Le Chili",
      "La Bolivie",
      "Le Machu Picchu est une ancienne cité inca située dans les Andes péruviennes.",
    ],
    [
      "Quelle est la capitale du Canada ?",
      "Ottawa",
      "Toronto",
      "Montréal",
      "Vancouver",
      "Ottawa est la capitale fédérale du Canada.",
    ],
    [
      "Sur quel continent se trouve le Sahara ?",
      "L’Afrique",
      "L’Asie",
      "L’Océanie",
      "L’Europe",
      "Le Sahara s’étend dans le nord de l’Afrique.",
    ],
    [
      "Quel fleuve traverse Paris ?",
      "La Seine",
      "La Loire",
      "Le Rhône",
      "La Garonne",
      "La Seine traverse Paris et se jette dans la Manche.",
    ],
    [
      "Quelle est la plus haute montagne au-dessus du niveau de la mer ?",
      "L’Everest",
      "Le K2",
      "Le mont Blanc",
      "Le Kilimandjaro",
      "L’Everest culmine à environ 8 849 mètres au-dessus du niveau de la mer.",
    ],
    [
      "Dans quel pays se trouve la ville de Marrakech ?",
      "Le Maroc",
      "La Tunisie",
      "L’Égypte",
      "L’Algérie",
      "Marrakech est une ville du Maroc, au pied du Haut Atlas.",
    ],
    [
      "Quel pays a la forme d’une botte sur une carte ?",
      "L’Italie",
      "La Suède",
      "Le Portugal",
      "La Grèce",
      "La péninsule italienne est souvent comparée à une botte.",
    ],
    [
      "Quelle est la capitale de l’Australie ?",
      "Canberra",
      "Sydney",
      "Melbourne",
      "Perth",
      "Canberra est la capitale de l’Australie depuis le début du XXe siècle.",
    ],
  ],
  science: [
    [
      "Quelle est la formule chimique de l’eau ?",
      "H₂O",
      "CO₂",
      "O₂",
      "NaCl",
      "Une molécule d’eau contient deux atomes d’hydrogène et un atome d’oxygène.",
    ],
    [
      "Quelle planète est surnommée la planète rouge ?",
      "Mars",
      "Vénus",
      "Jupiter",
      "Neptune",
      "Mars doit sa couleur rougeâtre aux oxydes de fer présents à sa surface.",
    ],
    [
      "Quel organe pompe le sang dans le corps ?",
      "Le cœur",
      "Le foie",
      "Le poumon",
      "Le rein",
      "Le cœur propulse le sang dans les vaisseaux sanguins.",
    ],
    [
      "Combien de côtés possède un hexagone ?",
      "Six",
      "Cinq",
      "Sept",
      "Huit",
      "Un hexagone est un polygone à six côtés.",
    ],
    [
      "Quelle étoile est au centre de notre système solaire ?",
      "Le Soleil",
      "Sirius",
      "Véga",
      "Polaris",
      "Le Soleil est l’étoile autour de laquelle gravitent les planètes du système solaire.",
    ],
    [
      "Quel gaz les plantes absorbent-elles lors de la photosynthèse ?",
      "Le dioxyde de carbone",
      "L’hélium",
      "Le néon",
      "L’argon",
      "La photosynthèse utilise le dioxyde de carbone et l’eau, avec l’énergie lumineuse.",
    ],
    [
      "Combien de pattes possède un insecte adulte ?",
      "Six",
      "Quatre",
      "Huit",
      "Dix",
      "Les insectes possèdent trois paires de pattes, soit six pattes.",
    ],
    [
      "Quelle est l’unité de la résistance électrique ?",
      "L’ohm",
      "Le volt",
      "L’ampère",
      "Le watt",
      "La résistance électrique se mesure en ohms, de symbole Ω.",
    ],
    [
      "À quelle température l’eau pure gèle-t-elle à pression atmosphérique normale ?",
      "0 °C",
      "10 °C",
      "50 °C",
      "100 °C",
      "À la pression atmosphérique normale, l’eau pure se solidifie à 0 °C.",
    ],
    [
      "Quel est le satellite naturel de la Terre ?",
      "La Lune",
      "Titan",
      "Europe",
      "Phobos",
      "La Lune est le seul satellite naturel permanent de la Terre.",
    ],
  ],
};
export const questions: Question[] = Object.entries(bank).flatMap(
  ([theme, rows]) =>
    rows.map((row, i) => ({
      id: `${theme}-${i + 1}`,
      theme: theme as ThemeId,
      text: row[0],
      choices: row.slice(1, 5),
      correct: 0,
      explanation: row[5],
    })),
);
export const themeById = (id: string) => themes.find((t) => t.id === id)!;
